# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliveSFU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AliveSFU
  pod ‘Firebase/Core’
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  

  target 'AliveSFUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AliveSFUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


#target 'JBChart' do
  ## Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for JBChart

  #target 'JBChartTests' do
    #inherit! :search_paths
    ## Pods for testing
  #end

#end
